### PR TITLE
Update dashboard links

### PR DESCRIPTION
**Pull request by misohu**
Related to: https://github.com/canonical/kubeflow-dashboard-operator/issues/190

[Some of the links in the configmap ](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/manifests/base/configmap.yaml#L7)changed upstream. This PR resolves the changes related to this charm.

### CODE REVIEW

**Comment by NohaIhab** [comment]
Updated from rc.2 [changes](https://github.com/kubeflow/manifests/compare/v1.9.0-rc.1...1.9.0-rc.2#files_bucket), a documentation link was added for Katib

## Testing instructions
```
juju deploy katib-ui --trust --channel=latest/edge/pr-189 --base ubuntu@20.04
juju deploy kubeflow-dashboard --trust --channel=latest/edge
juju deploy kubeflow-profiles --trust --channel=latest/edge

juju relate kubeflow-dashboard kubeflow-profiles
juju relate kubeflow-dashboard:links katib-ui:dashboard-links
```
Visit the IP of the `kubeflow-dashboard` pod with the port `8082`
expected webpage:
Screenshot from 2024-06-28 12-39-53

**Review by DnPlas — COMMENTED** [review]
Thanks @misohu ! Changes LGTM, but looks like the CI is complaining because of [this](https://github.com/canonical/katib-operators/actions/runs/9741485771/job/26880798479?pr=189#step:4:156). 

```
unit-katib-db-manager-0: 09:32:40 ERROR unit.katib-db-manager/0.juju-log mysql:8: Relation mysql is deprecated. Remove deprecated mysql relation to unblock.
```

Let's remove the deprecated relation in a separate PR and come back to this one.

**Comment by NohaIhab** [comment]
thx @DnPlas #207 is now ready for review to remove the deprecated relation

**Review by rgildein — COMMENTED** [review]
I tested it and it's working fine, can you check failing CI?

**Review by rgildein — APPROVED** [review]
LGTM

**Pull request merged**
