### PR TITLE
feat: get images on main

### LINKED ISSUE #131: Create a tool to get images that are referenced by Katib charms
# Description

A number of container images are referenced in Katib charms. There should be a script available to retrieve a complete list of images that can be deployed by Katib charms and its workloads.

This issue is related to the following:
https://github.com/canonical/bundle-kubeflow/issues/679
https://github.com/canonical/bundle-kubeflow/issues/674

# Solution
Create script that will parse required files that contain references to images managed by Katib charms.

### PR DESCRIPTION
**Pull request by NohaIhab**
fixes #131 
should be merged after #133

### CODE REVIEW

**Comment by i-chvets** [comment]
What about images in templates? Do we want to remove them from final list?

**Comment by kimwnasptd** [comment]
@i-chvets do you refer to the images we wanted to get rid, documented in https://github.com/canonical/katib-operators/issues/132?

In this case let's not block this PR on that (orthogonal) effort. We need the above for airgap to make sure we are gathering all images. Then we can have a follow-up one on how to remove the extra images, used in the templates

**Comment by i-chvets** [comment]
@kimwnasptd Adding this to keep track:
> Images in templates need to be addressed. Details are in https://github.com/canonical/katib-operators/issues/132
This work will be handled as a separate effort.

**Review by i-chvets — APPROVED** [review]
Added comments to keep track of extra work required.
LGTM. Approved. Pending CI passing.

**Pull request merged**
