### PR TITLE
Update the bug template

### PR DESCRIPTION
**Pull request by kimwnasptd**
Update the bug template, based on o11y team.

### CODE REVIEW

**Review by i-chvets — APPROVED** [review]
Approved.

**Comment by i-chvets** [comment]
@kimwnasptd This one is still in Draft.

**Comment by i-chvets** [comment]
@kimwnasptd I switched this one from draft for review ready. It is good to go. Let me know if there are any reservations. I will merge it before start of next business week.

**Comment by kimwnasptd** [comment]
@i-chvets should now be ready for review

**Pull request merged**
